<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::create([
            'uid' => null,
            'email' => 'tech2@lqhmarkets.com',
            'email_confirmed' => 1,
            'password' => Hash::make('tech2@lqhmarkets.com'),
            'country_code' => null,
            'number' => '+918955558855',
            'number_confirmed' => 0,
            'two_factor_enabled' => 0,
            'lockout_end_date' => null,
            'lockout_enabled' => 0,
            'access_count_failed' => 0,
            'username' => 'tech2@lqhmarkets.com',
            'profile_image_url' => null,
            'fullname' => 'Digvijay Singh',
            'byPartner' => 0,
            'date' => null,
            'status' => 1,
            'country' => 'India',
            'dial_code' => null,
            'Isreferal' => 0,
            'referalId' => null,
            'zipcode' => null,
            'address' => null,
            'aboutme' => null,
            'imgName' => null,
            'education' => null,
            'industry' => null,
            'financial_industry' => null,
            'forex_exp' => null,
            'monthly_transaction' => null,
            'investment_plan' => null,
            'funds_source' => null,
            'investment_purpose' => null,
            'total_value' => null,
            'annual_income' => null,
            'polotically_person' => null,
            'bankruptcy' => null,
            'usa_resident' => null,
            'usa_tax' => null,
            'dob' => null,
            'emailToken' => 'IMMYes8RskI8VPHQfol2SlUrcV4sJjg9DTxVZFjQ81J0S9NjmnoG9Fkh0jiU',
            'state' => null,
            'city' => null,
            'lang' => 'english',
            'email_token_time' => '2024-11-22 18:35:15',
            'profile_image' => null,
            'gender' => null,
            'referral' => '',
            'mail_otp' => null,
            'employee_status' => null,
            'cfd' => null,
            'other' => null,
            'kyc_type' => null,
            'kyc_front' => null,
            'kyc_back' => null,
            'bank_detail' => null,
            'account_holder_name' => null,
            'bank_name' => null,
            'bank_account_no' => null,
            'IFSC_Code' => null,
            'swift_code' => null,
            'kyc_verify' => 1,
            'client_status' => 0,
            'wallet_address' => null,
            'reg_date' => '2024-11-22 13:05:59',
            'bank_status' => 0,
            'personal_status' => 0,
            'employemnet_status' => 0,
            'trading_status' => 0,
            'ib1' => '',
            'ib2' => null,
            'ib3' => null,
            'ib4' => null,
            'ib5' => null,
            'ib6' => null,
            'ib7' => null,
            'ib8' => null,
            'ib9' => null,
            'ib10' => null,
            'ib11' => null,
            'ib12' => null,
            'ib13' => null,
            'ib14' => null,
            'ib15' => null,
            'wallet_requested' => null,
            'wallet_enabled' => null,
            'wallet_requested_at' => null,
            'wallet_approved_at' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
    }
}
