<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateSymbolsTable extends Migration
{
    public function up()
    {
        Schema::create('symbols', function (Blueprint $table) {
            $table->id();
            $table->string('symbol');
            $table->string('path');
            $table->string('isin')->nullable();
            $table->string('description');
            $table->string('international')->nullable();
            $table->string('basis')->nullable();
            $table->string('source')->nullable();
            $table->string('page')->nullable();
            $table->string('currency_base');
            $table->integer('currency_base_digits');
            $table->string('currency_profit');
            $table->integer('currency_profit_digits');
            $table->string('currency_margin');
            $table->integer('currency_margin_digits');
            $table->bigInteger('color');
            $table->bigInteger('color_background');
            $table->integer('digits');
            $table->float('point');
            $table->integer('multiply');
            $table->integer('tick_flags');
            $table->integer('tick_book_depth');
            $table->integer('chart_mode');
            $table->integer('filter_soft');
            $table->integer('filter_soft_ticks');
            $table->integer('filter_hard');
            $table->integer('filter_hard_ticks');
            $table->integer('filter_discard');
            $table->integer('filter_spread_max');
            $table->integer('filter_spread_min');
            $table->integer('filter_gap');
            $table->integer('filter_gap_ticks');
            $table->integer('trade_mode');
            $table->integer('trade_flags');
            $table->integer('calc_mode');
            $table->integer('exec_mode');
            $table->integer('gtc_mode');
            $table->integer('fill_flags');
            $table->integer('expir_flags');
            $table->integer('order_flags');
            $table->float('spread');
            $table->float('spread_balance');
            $table->float('spread_diff');
            $table->float('spread_diff_balance');
            $table->float('tick_value');
            $table->float('tick_size');
            $table->integer('contract_size');
            $table->integer('stops_level');
            $table->integer('freeze_level');
            $table->integer('quotes_timeout');
            $table->integer('volume_min');
            $table->bigInteger('volume_min_ext');
            $table->bigInteger('volume_max');
            $table->bigInteger('volume_max_ext');
            $table->bigInteger('volume_step');
            $table->bigInteger('volume_step_ext');
            $table->integer('volume_limit');
            $table->integer('volume_limit_ext');
            $table->integer('margin_flags');
            $table->float('margin_initial');
            $table->float('margin_maintenance');
            $table->json('margin_rate_initial');
            $table->json('margin_rate_maintenance');
            $table->float('margin_rate_liquidity');
            $table->integer('margin_hedged');
            $table->float('margin_rate_currency');
            $table->float('margin_long');
            $table->float('margin_short');
            $table->integer('margin_limit');
            $table->integer('margin_stop');
            $table->integer('margin_stop_limit');
            $table->integer('swap_mode');
            $table->float('swap_long');
            $table->float('swap_short');
            $table->integer('swap_3_day');
            $table->integer('time_start');
            $table->integer('time_expiration');
            $table->json('sessions_quotes')->nullable();
            $table->json('sessions_trades')->nullable();
            $table->integer('re_flags');
            $table->integer('re_timeout');
            $table->integer('ie_check_mode');
            $table->integer('ie_timeout');
            $table->integer('ie_slip_profit');
            $table->integer('ie_slip_losing');
            $table->integer('ie_volume_max');
            $table->integer('ie_volume_max_ext');
            $table->float('price_settle');
            $table->float('price_limit_max');
            $table->float('price_limit_min');
            $table->float('price_strike');
            $table->integer('options_mode');
            $table->float('face_value');
            $table->float('accrued_interest');
            $table->integer('splice_type');
            $table->integer('splice_time_type');
            $table->integer('splice_time_days');
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('symbols');
    }
}